### ISSUE TITLE
Adding install package to CMakeList

### ISSUE THREAD

**Issue by benkonz** [oliora/bitmask#1]
Would it be possible to add a way to install this library in the CMakeLists.txt as a package? It would be a lot simpler to use this library if there was a way to download the source code -> make -> make install -> add a find_packge(bitmask), rather than hard coding the header location to the include location. If it is too much work for you, I could try to adjust the CMakeList to add the code to install the package with all of the bitmaskConfig.cmake files so that it works with find_package and make a pull request to update it on the Master branch.

**Comment by oliora** [comment]
I've added install script.
Unfortunately I have to get rid of `boost` namespace because of directory collision. Now everything is in `bitmask` namespace. Macro names to define bitmasks are also changed.
Please check readme for installation steps and new names.
Sorry for inconvenience.
And the last one. I've changed license from public domain to boost.Let me know if it doesn't fit your usage.

**Comment by oliora** [comment]
Feel free to reopen issue

**Comment by benkonz** [comment]
Just tested it, works great. Thanks!
